### ISSUE TITLE
Setup unit tests

### ISSUE THREAD

**Issue by yannbf** [bitfindr/bitfindr#41]

**Comment by kshaaban-** [comment]
Unit Testing (and testing in generally) has always been an issue for ionic apps.
The solution I'm working on at [setup-test-env](https://github.com/bitfindr/bitfindr/tree/feature/setup-test-env) branch is based on [this project](https://github.com/lathonez/clicker) -- and [this blog post](http://lathonez.com/2017/ionic-2-unit-testing)

Currently, the branch includes all env setup. And tests can be run with `npm test`.
Upon running, you'll immediately notice that our project is lacking mocks for its own providers/services. Therefore tests won't run successfully until we provide test-doubles/mocks in our `TestingModule` so that our components do not have any external dependencies when being unit tested.

There's already a great mocking library out there for ionic services/providers called [ionic-mocks](https://github.com/stonelasley/ionic-mocks) -- It would be a good place to look at how services are being mocked, and then doing something similar to our services/providers.

I was thinking of having all our mocks live in a folder `src/mocks` to create mocks for our providers and provide them in `src/test.ts`

**Comment by yannbf** [comment]
Awesome start!
Here's some material for our reference:
[Ionic testing starter project](https://github.com/ionic-team/ionic-unit-testing-example)

For mocks:
**[ionic-mocks](https://github.com/stonelasley/ionic-mocks)**
**[ionic-test-doubles](https://github.com/DomesticApp/ionic-test-doubles)**
**[ionic-native-mocks](https://github.com/chrisgriffith/ionic-native-mocks)**
